# apiVersion: ricoberger.de/v1alpha1
# kind: VaultSecret
# metadata:
#   name: vaultsecret-sample
# spec:
#   keys:
#     - foo
#   path: kvv1/example-vaultsecret
#   type: Opaque
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: api-client-ca
  namespace: nginx-ingress
spec:
  isBinary: false
  reconcileStrategy: Merge
  paths: 
    ca_root: "pki/cert/ca"
    ca_api: "pki_api/cert/ca"
    crl_root: "pki/cert/crl"
    crl_api: "pki_api/cert/crl"
  templates: 
    ca.crt: "{% .ca_root.Secrets.certificate %}\n{% .ca_api.Secrets.certificate %}"
    ca.crl: "{% .ca_crl.Secrets.certificate %}\n{% .ca_crl.Secrets.certificate %}"
  type: Opaque